apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui2
spec:
  replicas: 2
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: guestbook-ui2
  template:
    metadata:
      labels:
        app: guestbook-ui2
    spec:
      containers:
      - image: docker.io/tsuyito/test-nginx:0.0.1
        name: guestbook-ui2
        ports:
        - containerPort: 80
